from . import res_partner_inherit
from . import sh_doctor_commission
from . import sh_specialization
from . import sh_allergies
from . import sh_allergy_type
from . import sh_commission_type
from . import sh_ingredients
from . import sh_medicine_form
from . import product_template_inherit 
from . import sale_order_inherit
from . import sale_order_line_inherit
from . import product_category_inherit
from . import sh_split_wizard