# -*- coding: utf-8 -*-
# Copyright (C) Softhealer Technologies.
{
    'name':'SH Pharmacy Management System',
    'version':'1.0',
    'sequence':1,
    'summary':'SH Pharmacy Management System',
    'description':'SH Pharmacy Management System',
    'depends':['sale_management',
               'purchase',
               'contacts',
               'stock',
               'point_of_sale',                          
               'hr',
               'fleet'],
    'data':[        
        'security/ir.model.access.csv',  
        'views/sh_res_partner_view_inherit.xml',
        'views/sh_specialization_views.xml',
        'views/sh_commission_type_views.xml',
        'views/sh_doctor_commission_views.xml',
        'views/sh_allergies_views.xml',
        'views/sh_allergy_type_views.xml',
        'views/sh_ingredients_views.xml',
        'views/sh_product_category_inherit_views.xml',
        'views/sh_medicine_form_views.xml',
        'views/sh_sale_order_inherit_views.xml',
        'views/sh_product_template_inherit_views.xml',
        'wizard/sh_pharmacy_report_wizard_views.xml',        
        'views/sh_pharmacy_menu.xml',
        'wizard/sh_split_wizard_views.xml',
        ],
    'images':['static/description/pharmacy.png'],
    'installable':True,
    'application':True,
    'license': 'LGPL-3',
}